# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /test/CMakeFiles /test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nanotekspice

# Build rule for target.
nanotekspice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanotekspice
.PHONY : nanotekspice

# fast build rule for target.
nanotekspice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/build
.PHONY : nanotekspice/fast

src/Circuit/Circuit.o: src/Circuit/Circuit.cpp.o
.PHONY : src/Circuit/Circuit.o

# target to build an object file
src/Circuit/Circuit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Circuit/Circuit.cpp.o
.PHONY : src/Circuit/Circuit.cpp.o

src/Circuit/Circuit.i: src/Circuit/Circuit.cpp.i
.PHONY : src/Circuit/Circuit.i

# target to preprocess a source file
src/Circuit/Circuit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Circuit/Circuit.cpp.i
.PHONY : src/Circuit/Circuit.cpp.i

src/Circuit/Circuit.s: src/Circuit/Circuit.cpp.s
.PHONY : src/Circuit/Circuit.s

# target to generate assembly for a file
src/Circuit/Circuit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Circuit/Circuit.cpp.s
.PHONY : src/Circuit/Circuit.cpp.s

src/Components/AdvancedComponents/FourBitsAdder.o: src/Components/AdvancedComponents/FourBitsAdder.cpp.o
.PHONY : src/Components/AdvancedComponents/FourBitsAdder.o

# target to build an object file
src/Components/AdvancedComponents/FourBitsAdder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/AdvancedComponents/FourBitsAdder.cpp.o
.PHONY : src/Components/AdvancedComponents/FourBitsAdder.cpp.o

src/Components/AdvancedComponents/FourBitsAdder.i: src/Components/AdvancedComponents/FourBitsAdder.cpp.i
.PHONY : src/Components/AdvancedComponents/FourBitsAdder.i

# target to preprocess a source file
src/Components/AdvancedComponents/FourBitsAdder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/AdvancedComponents/FourBitsAdder.cpp.i
.PHONY : src/Components/AdvancedComponents/FourBitsAdder.cpp.i

src/Components/AdvancedComponents/FourBitsAdder.s: src/Components/AdvancedComponents/FourBitsAdder.cpp.s
.PHONY : src/Components/AdvancedComponents/FourBitsAdder.s

# target to generate assembly for a file
src/Components/AdvancedComponents/FourBitsAdder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/AdvancedComponents/FourBitsAdder.cpp.s
.PHONY : src/Components/AdvancedComponents/FourBitsAdder.cpp.s

src/Components/GatesComponents/AndGate.o: src/Components/GatesComponents/AndGate.cpp.o
.PHONY : src/Components/GatesComponents/AndGate.o

# target to build an object file
src/Components/GatesComponents/AndGate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/GatesComponents/AndGate.cpp.o
.PHONY : src/Components/GatesComponents/AndGate.cpp.o

src/Components/GatesComponents/AndGate.i: src/Components/GatesComponents/AndGate.cpp.i
.PHONY : src/Components/GatesComponents/AndGate.i

# target to preprocess a source file
src/Components/GatesComponents/AndGate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/GatesComponents/AndGate.cpp.i
.PHONY : src/Components/GatesComponents/AndGate.cpp.i

src/Components/GatesComponents/AndGate.s: src/Components/GatesComponents/AndGate.cpp.s
.PHONY : src/Components/GatesComponents/AndGate.s

# target to generate assembly for a file
src/Components/GatesComponents/AndGate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/GatesComponents/AndGate.cpp.s
.PHONY : src/Components/GatesComponents/AndGate.cpp.s

src/Components/SpecialComponents/Input.o: src/Components/SpecialComponents/Input.cpp.o
.PHONY : src/Components/SpecialComponents/Input.o

# target to build an object file
src/Components/SpecialComponents/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/SpecialComponents/Input.cpp.o
.PHONY : src/Components/SpecialComponents/Input.cpp.o

src/Components/SpecialComponents/Input.i: src/Components/SpecialComponents/Input.cpp.i
.PHONY : src/Components/SpecialComponents/Input.i

# target to preprocess a source file
src/Components/SpecialComponents/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/SpecialComponents/Input.cpp.i
.PHONY : src/Components/SpecialComponents/Input.cpp.i

src/Components/SpecialComponents/Input.s: src/Components/SpecialComponents/Input.cpp.s
.PHONY : src/Components/SpecialComponents/Input.s

# target to generate assembly for a file
src/Components/SpecialComponents/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/SpecialComponents/Input.cpp.s
.PHONY : src/Components/SpecialComponents/Input.cpp.s

src/Components/SpecialComponents/Out.o: src/Components/SpecialComponents/Out.cpp.o
.PHONY : src/Components/SpecialComponents/Out.o

# target to build an object file
src/Components/SpecialComponents/Out.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/SpecialComponents/Out.cpp.o
.PHONY : src/Components/SpecialComponents/Out.cpp.o

src/Components/SpecialComponents/Out.i: src/Components/SpecialComponents/Out.cpp.i
.PHONY : src/Components/SpecialComponents/Out.i

# target to preprocess a source file
src/Components/SpecialComponents/Out.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/SpecialComponents/Out.cpp.i
.PHONY : src/Components/SpecialComponents/Out.cpp.i

src/Components/SpecialComponents/Out.s: src/Components/SpecialComponents/Out.cpp.s
.PHONY : src/Components/SpecialComponents/Out.s

# target to generate assembly for a file
src/Components/SpecialComponents/Out.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Components/SpecialComponents/Out.cpp.s
.PHONY : src/Components/SpecialComponents/Out.cpp.s

src/Factory/Factory.o: src/Factory/Factory.cpp.o
.PHONY : src/Factory/Factory.o

# target to build an object file
src/Factory/Factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Factory/Factory.cpp.o
.PHONY : src/Factory/Factory.cpp.o

src/Factory/Factory.i: src/Factory/Factory.cpp.i
.PHONY : src/Factory/Factory.i

# target to preprocess a source file
src/Factory/Factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Factory/Factory.cpp.i
.PHONY : src/Factory/Factory.cpp.i

src/Factory/Factory.s: src/Factory/Factory.cpp.s
.PHONY : src/Factory/Factory.s

# target to generate assembly for a file
src/Factory/Factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/Factory/Factory.cpp.s
.PHONY : src/Factory/Factory.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nanotekspice"
	@echo "... src/Circuit/Circuit.o"
	@echo "... src/Circuit/Circuit.i"
	@echo "... src/Circuit/Circuit.s"
	@echo "... src/Components/AdvancedComponents/FourBitsAdder.o"
	@echo "... src/Components/AdvancedComponents/FourBitsAdder.i"
	@echo "... src/Components/AdvancedComponents/FourBitsAdder.s"
	@echo "... src/Components/GatesComponents/AndGate.o"
	@echo "... src/Components/GatesComponents/AndGate.i"
	@echo "... src/Components/GatesComponents/AndGate.s"
	@echo "... src/Components/SpecialComponents/Input.o"
	@echo "... src/Components/SpecialComponents/Input.i"
	@echo "... src/Components/SpecialComponents/Input.s"
	@echo "... src/Components/SpecialComponents/Out.o"
	@echo "... src/Components/SpecialComponents/Out.i"
	@echo "... src/Components/SpecialComponents/Out.s"
	@echo "... src/Factory/Factory.o"
	@echo "... src/Factory/Factory.i"
	@echo "... src/Factory/Factory.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

